security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: cin

    firewalls:
        main:
            pattern: ^/
            provider: app_user_provider
            lazy: true
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
                - App\Security\GoogleAuthenticator
            logout:
                path: app_logout
                target: app_login

        
    


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10