# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    twilio_sid: '%env(TWILIO_SID)%'
    twilio_token: '%env(TWILIO_AUTH_TOKEN)%'
    twilio_from: '%env(TWILIO_PHONE_NUMBER)%'
    chatbot_api_url: '%env(SECRET_KEY_CHATBOT)%'
    recaptcha_secret: '%env(NOCAPTCHA_SECRET)%'
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    App\Factory\StripeServiceFactory:
        arguments: ['%env(STRIPE_SECRET_KEY)%']
    App\Service\StripeService:
        arguments:
            factory: ['@App\Factory\StripeServiceFactory', 'create']
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\TwilioService:
        arguments:
            $accountSid: '%twilio_sid%'
            $authToken: '%twilio_token%'
    App\Service\GeminiChatbotService:
        arguments:
            $chatbotApiUrl: '%chatbot_api_url%'
    App\Service\CaptchaValidator:
        arguments:
            $recaptchaSecret: '%recaptcha_secret%'
    App\Service\SendGridMailer:
        arguments:
            $sendGridApiKey: '%env(SENDGRID_API_KEY)%'
    